name: Compile Meerkat2-average

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest


    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: "Check selected compiler"
      run: |
        cmake --help


    - name: Compile Meerkat2-average
      run: |
        mkdir meerkat2-average-build
        cd meerkat2-average-build
        cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE:STRING="Release"  ..
        cmake --build .
        ls

    - name: Test Meerkat2-average
      run: |
        cd meerkat2-average-build
        ctest --extra-verbose

    - name: Upload compiled linux
      uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        name: meerkat2-average-linux
        path: meerkat2-average-build/meerkat2-average

    - name: Upload compiled file windows
      uses: actions/upload-artifact@v4
      if: matrix.os == 'windows-latest'
      with:
        name: meerkat2-average.exe
        path: meerkat2-average-build/meerkat2-average.exe


